name: 'Dad. Single. Go!'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.12138
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050308'
    - '#951718'
    - '#da2c2f'
    - '#a3abda'
    - '#8a7cd1'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.45924537093378603
  rhythmicContrast: 0.9127680559176952
purpose: []
