name: 'Dad. Single. Go!'
favicon: null
layout_spectrum: 0.91735
typography_spectrum: 0.1247289627790451
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a3b6d7'
    - '#8d8a6b'
    - '#382622'
    - '#f2eee3'
    - '#7a4631'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.45924537093378603
  rhythmicContrast: 0.9127680559176952
purpose: []
